# Generated by Django 6.1 on 2026-08-13 07:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_delta', models.DecimalField(decimal_places=3, max_digits=16)),
                ('reason', models.CharField(choices=[('opening_stock', 'Opening Stock'), ('purchase', 'Stock Purchase'), ('sale', 'Sale'), ('customer_return', 'Customer Return'), ('supplier_return', 'Supplier Return'), ('damage', 'Damage'), ('expiry', 'Expiry'), ('adjustment', 'Stock Adjustment'), ('branch_transfer_out', 'Branch Transfer Out'), ('branch_transfer_in', 'Branch Transfer In'), ('promotional_sample', 'Promotional Sample'), ('personal_use', 'Personal Use'), ('other', 'Other Authorized Movement')], max_length=30)),
                ('reference_note', models.CharField(blank=True, max_length=255)),
                ('source_type', models.CharField(blank=True, max_length=50)),
                ('source_id', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=16)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_levels', to='tenants.branch')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.business')),
            ],
        ),
    ]
