# Generated by Django 6.1 on 2026-08-15 12:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stocktransfer'),
        ('products', '0002_pricehistory'),
        ('tenants', '0003_business_paystack_public_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='client_reference',
            field=models.CharField(blank=True, help_text='Client-generated idempotency key for movements queued while offline, so a retried sync request can never post the same adjustment twice.', max_length=64, null=True),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.UniqueConstraint(condition=models.Q(('client_reference__isnull', False)), fields=('business', 'client_reference'), name='unique_movement_client_reference_per_business'),
        ),
    ]
