# Generated by Django 6.1 on 2026-08-14 08:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_business_ai_addon_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.CharField(choices=[('critical', 'Critical'), ('important', 'Important'), ('info', 'Information')], default='info', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('whatsapp_attempted', models.BooleanField(default=False)),
                ('whatsapp_delivered', models.BooleanField(default=False)),
                ('whatsapp_error', models.CharField(blank=True, max_length=500)),
                ('email_attempted', models.BooleanField(default=False)),
                ('email_delivered', models.BooleanField(default=False)),
                ('email_error', models.CharField(blank=True, max_length=500)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='tenants.branch')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.business')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
