# Generated by Django 6.1 on 2026-08-14 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_access_token', models.CharField(blank=True, max_length=500)),
                ('whatsapp_phone_number_id', models.CharField(blank=True, max_length=100)),
                ('email_host_user', models.CharField(blank=True, max_length=255)),
                ('email_host_password', models.CharField(blank=True, help_text='A Gmail App Password, not the account password. Stored as-is for now — encrypt at rest in production.', max_length=255)),
                ('platform_paystack_public_key', models.CharField(blank=True, max_length=200)),
                ('platform_paystack_secret_key', models.CharField(blank=True, max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform Settings',
                'verbose_name_plural': 'Platform Settings',
            },
        ),
    ]
