# Generated by Django 6.1 on 2026-08-20 00:00
# NOTE: hand-written (no Django available in the review sandbox) — run
# `python manage.py makemigrations --check` before applying.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_platformsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='rent_mode_enabled',
            field=models.BooleanField(
                default=False,
                help_text="Master switch for paid-feature enforcement. OFF: every feature is unlocked for "
                          "every business, regardless of subscription — billing exists but isn't enforced. "
                          "ON: gated features (see billing.Feature) require an active Plan or an admin "
                          "override. Meant to be flipped freely — e.g. off during a demo or free period, "
                          "on when you're ready to start charging — with no other changes needed.",
            ),
        ),
    ]
