# Generated by Django 6.1 on 2026-08-21 00:00
# NOTE: hand-written (no Django available in the review sandbox) — run
# `python manage.py makemigrations --check` before applying. This
# migration changes the field class only — the underlying database
# column is unaffected (still varchar), so it's safe to run even with
# existing plaintext data; those rows will just be read as-is until
# next saved, at which point they become encrypted.

import apps.core.crypto
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_platformsettings_rent_mode_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformsettings',
            name='whatsapp_access_token',
            field=apps.core.crypto.EncryptedCharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='email_host_password',
            field=apps.core.crypto.EncryptedCharField(
                blank=True, max_length=500,
                help_text="A Gmail App Password, not the account password. Encrypted at rest.",
            ),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='platform_paystack_secret_key',
            field=apps.core.crypto.EncryptedCharField(blank=True, max_length=500),
        ),
    ]
