# Generated by Django 6.1 on 2026-08-16 09:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
        ('tenants', '0005_business_default_tax_rate_percent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='client_reference',
            field=models.CharField(blank=True, help_text='Client-generated idempotency key for expenses recorded while offline.', max_length=64, null=True),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.UniqueConstraint(condition=models.Q(('client_reference__isnull', False)), fields=('business', 'client_reference'), name='unique_expense_client_reference_per_business'),
        ),
    ]
