# Generated by Django 6.1 on 2026-08-20 00:00
# NOTE: hand-written (no Django available in the review sandbox to run
# makemigrations) — run `python manage.py makemigrations --check` on
# your machine before applying; if it reports any drift, run
# `makemigrations billing` to regenerate this file from the models.

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0005_business_default_tax_rate_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(help_text="Stable identifier checked in code, e.g. 'ai_addon'.", max_length=60, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive features are hidden from new Plans but existing grants still work.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('price_amount', models.DecimalField(decimal_places=2, help_text='In the currency below, e.g. 5000.00.', max_digits=12)),
                ('currency', models.CharField(default='NGN', max_length=8)),
                ('billing_interval', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=10)),
                ('paystack_plan_code', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive plans are hidden from the upgrade page but existing subscribers keep their access.')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('features', models.ManyToManyField(blank=True, related_name='plans', to='billing.feature')),
            ],
            options={
                'ordering': ['sort_order', 'price_amount'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('none', 'No subscription'), ('pending', 'Pending first payment'), ('active', 'Active'), ('past_due', 'Payment failed / past due'), ('canceled', 'Canceled')], default='none', max_length=12)),
                ('paystack_customer_code', models.CharField(blank=True, max_length=100)),
                ('paystack_subscription_code', models.CharField(blank=True, max_length=100)),
                ('paystack_email_token', models.CharField(blank=True, help_text='Required by Paystack to manage/cancel the subscription via API.', max_length=200)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='tenants.business')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.plan')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='FeatureOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_enabled', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, help_text="Why this override exists, e.g. 'trial until launch', 'comped for beta tester'.", max_length=255)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Leave blank for a permanent override.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_overrides', to='tenants.business')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='billing.feature')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='BillingEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=100)),
                ('paystack_reference', models.CharField(blank=True, max_length=100)),
                ('raw_payload', models.JSONField(default=dict)),
                ('processed_ok', models.BooleanField(default=False)),
                ('error', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_events', to='tenants.business')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='featureoverride',
            unique_together={('business', 'feature')},
        ),
    ]
