# Generated by Django 6.1 on 2026-08-13 07:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opening_cash', models.DecimalField(decimal_places=2, max_digits=14)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closing_physical_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('expected_closing_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('variance', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('pending_review', 'Pending Review'), ('reviewed', 'Reviewed')], default='open', max_length=20)),
                ('result', models.CharField(blank=True, choices=[('balanced', 'Balanced'), ('over', 'Cash Over'), ('short', 'Cash Short'), ('requires_review', 'Requires Review')], max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.CharField(blank=True, max_length=500)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to='tenants.branch')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.business')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_shifts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
    ]
