# Generated by Django 6.1 on 2026-08-21 00:00
# NOTE: hand-written (no Django available in the review sandbox) — run
# `python manage.py makemigrations --check` before applying.

import apps.core.crypto
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_usersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='two_factor_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_secret',
            field=apps.core.crypto.EncryptedCharField(
                blank=True, max_length=500,
                help_text="TOTP secret, encrypted at rest. Blank until setup is confirmed (see accounts.views 2FA endpoints).",
            ),
        ),
    ]
