# Generated by Django 6.1 on 2026-08-12 23:21

import apps.tenants.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('business_type', models.CharField(choices=[('retail', 'Retail / Shop'), ('wholesale', 'Wholesale'), ('provisions', 'Provision Store'), ('boutique', 'Boutique'), ('pharmacy', 'Pharmacy'), ('restaurant', 'Restaurant'), ('kiosk', 'Kiosk'), ('supermarket', 'Supermarket'), ('other', 'Other')], default='retail', max_length=30)),
                ('logo', models.ImageField(blank=True, help_text='Displayed on every receipt, invoice, statement, and report header.', null=True, upload_to=apps.tenants.models.business_logo_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'webp', 'svg'])])),
                ('address', models.CharField(blank=True, max_length=500)),
                ('phone_number', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('receipt_header_note', models.CharField(blank=True, help_text='Optional line shown under the business name on documents, e.g. a tagline.', max_length=255)),
                ('receipt_footer_note', models.CharField(blank=True, default='Thank you for your patronage!', help_text='Owner-editable line at the bottom of receipts, e.g. return policy.', max_length=255)),
                ('currency_code', models.CharField(default='NGN', max_length=8)),
                ('timezone', models.CharField(default='Africa/Lagos', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_businesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('phone_number', models.CharField(blank=True, max_length=50)),
                ('logo', models.ImageField(blank=True, help_text="Overrides the business logo on this branch's documents. Leave blank to inherit.", null=True, upload_to=apps.tenants.models.business_logo_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'webp', 'svg'])])),
                ('is_active', models.BooleanField(default=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='tenants.business')),
            ],
            options={
                'ordering': ['business', 'name'],
                'unique_together': {('business', 'name')},
            },
        ),
    ]
