# Generated by Django 6.1 on 2026-08-14 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='ai_addon_enabled',
            field=models.BooleanField(default=False, help_text="AI features (voice bookkeeping, receipt scanning, 'ask my business') are a paid add-on, gated by this flag once billing/subscription is wired up."),
        ),
        migrations.AddField(
            model_name='business',
            name='notification_email',
            field=models.EmailField(blank=True, help_text='Where alerts are sent via email. Defaults to the business email if blank.', max_length=254),
        ),
        migrations.AddField(
            model_name='business',
            name='notification_whatsapp_number',
            field=models.CharField(blank=True, help_text='E.164 format, e.g. +2348012345678. Where critical/important alerts are sent via WhatsApp.', max_length=32),
        ),
    ]
