# Generated by Django 6.1 on 2026-08-14 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_business_ai_addon_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='paystack_public_key',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='business',
            name='paystack_secret_key',
            field=models.CharField(blank=True, help_text='Stored as-is for now; in a production deployment this should be encrypted at rest (e.g. via django-encrypted-model-fields) rather than plain text.', max_length=200),
        ),
    ]
