# Generated by Django 6.1 on 2026-08-15 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_business_paystack_public_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='away_mode_discount_threshold_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="A discount above this % of a sale line's value triggers an immediate alert.", max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='away_mode_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='business',
            name='away_mode_price_change_threshold_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='A cost-price change above this % triggers an immediate alert.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='away_mode_refund_threshold_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='A refund above this amount triggers an immediate alert (refunds already require approval regardless).', max_digits=14, null=True),
        ),
    ]
