# Generated by Django 6.1 on 2026-08-16 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_business_away_mode_discount_threshold_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='default_tax_rate_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Applied automatically at POS checkout when set. Leave blank for no default tax.', max_digits=5, null=True),
        ),
    ]
