# Generated by Django 6.1 on 2026-08-21 00:00
# NOTE: hand-written (no Django available in the review sandbox) — run
# `python manage.py makemigrations --check` before applying.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_business_default_tax_rate_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='parent_branch',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='sub_branches', to='tenants.branch',
                help_text="For businesses with many locations: set this to make a branch a "
                          "'mini-branch' under a main one, for organization. A branch with no "
                          "parent is a main branch. Data access isn't restricted by this "
                          "hierarchy — it's organizational, not a permission boundary.",
            ),
        ),
    ]
