# Generated by hand, matching Django 6.1 migration format used elsewhere in this app.

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_branch_parent_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='theme_color',
            field=models.CharField(
                blank=True,
                default='#E3A635',
                help_text="Hex accent color (e.g. #E3A635) applied across the app's sidebar and highlights "
                          "for this business — owner/admin editable from Settings, no code change needed.",
                max_length=7,
                validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Enter a hex color like #E3A635.')],
            ),
        ),
    ]
