# Generated by Django 6.1 on 2026-08-14 08:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('sales', '0002_initial'),
        ('shifts', '0001_initial'),
        ('tenants', '0002_business_ai_addon_enabled_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='client_reference',
            field=models.CharField(blank=True, help_text='Client-generated idempotency key. Set when a sale is created from an offline queue so a retried sync request can never post the same sale twice.', max_length=64, null=True),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['business', 'client_reference'], name='sales_sale_busines_a33611_idx'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.UniqueConstraint(condition=models.Q(('client_reference__isnull', False)), fields=('business', 'client_reference'), name='unique_client_reference_per_business'),
        ),
    ]
