# Generated by Django 6.1 on 2026-08-18 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_sale_client_reference_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='reconciled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='reconciled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='reconciliation_note',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='payment',
            name='reconciliation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('reconciled', 'Reconciled'), ('unmatched', 'Unmatched'), ('disputed', 'Disputed')], default='pending', help_text='Cash is self-evident at the till; bank transfer/card/other payments start pending until matched against a bank or processor statement.', max_length=20),
        ),
    ]
