# Generated by Django 6.1 on 2026-08-20 00:00
# NOTE: hand-written (no Django available in the review sandbox) — run
# `python manage.py makemigrations --check` before applying; if it
# reports drift, regenerate with `makemigrations sales`.

import uuid
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0005_business_default_tax_rate_percent'),
        ('sales', '0004_payment_reconciled_at_payment_reconciled_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency_code', models.CharField(help_text="The foreign currency, e.g. 'USD'.", max_length=8)),
                ('rate_to_business_currency', models.DecimalField(decimal_places=6, help_text="1 unit of currency_code = this many units of the business's own currency.", max_digits=14, validators=[django.core.validators.MinValueValidator(1e-06)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_rates', to='tenants.business')),
                ('set_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='exchangerate',
            index=models.Index(fields=['business', 'currency_code', '-created_at'], name='sales_excha_busines_idx'),
        ),
        migrations.AddField(
            model_name='payment',
            name='foreign_currency_code',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='payment',
            name='foreign_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='exchange_rate_used',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True,
                                       help_text='Rate actually used for this payment — captured at the time, even '
                                                 'if the reference ExchangeRate is edited or deleted later.'),
        ),
    ]
